# permissions for end users to view builders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: builder-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cloudrun
    app.kubernetes.io/part-of: cloudrun
    app.kubernetes.io/managed-by: kustomize
  name: builder-viewer-role
rules:
- apiGroups:
  - cloudapi.scs.buaa.edu.cn
  resources:
  - builders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudapi.scs.buaa.edu.cn
  resources:
  - builders/status
  verbs:
  - get
