# permissions for end users to edit deployers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: deployer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cloudrun
    app.kubernetes.io/part-of: cloudrun
    app.kubernetes.io/managed-by: kustomize
  name: deployer-editor-role
rules:
- apiGroups:
  - cloudapi.scs.buaa.edu.cn
  resources:
  - deployers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudapi.scs.buaa.edu.cn
  resources:
  - deployers/status
  verbs:
  - get
