---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloudapi.scs.buaa.edu.cn
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudapi.scs.buaa.edu.cn
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - cloudapi.scs.buaa.edu.cn
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloudapi.scs.buaa.edu.cn
  resources:
  - builders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudapi.scs.buaa.edu.cn
  resources:
  - builders/finalizers
  verbs:
  - update
- apiGroups:
  - cloudapi.scs.buaa.edu.cn
  resources:
  - builders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloudapi.scs.buaa.edu.cn
  resources:
  - deployers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudapi.scs.buaa.edu.cn
  resources:
  - deployers/finalizers
  verbs:
  - update
- apiGroups:
  - cloudapi.scs.buaa.edu.cn
  resources:
  - deployers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloudapi.scs.buaa.edu.cn
  resources:
  - resourcepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudapi.scs.buaa.edu.cn
  resources:
  - resourcepools/finalizers
  verbs:
  - update
- apiGroups:
  - cloudapi.scs.buaa.edu.cn
  resources:
  - resourcepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloudapi.scs.buaa.edu.cn
  resources:
  - workflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudapi.scs.buaa.edu.cn
  resources:
  - workflows/finalizers
  verbs:
  - update
- apiGroups:
  - cloudapi.scs.buaa.edu.cn
  resources:
  - workflows/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
