apiVersion: cloudapi.scs.buaa.edu.cn/v1alpha1
kind: Deployer
metadata:
  labels:
    app.kubernetes.io/name: deployer
    app.kubernetes.io/instance: deployer-sample
    app.kubernetes.io/part-of: cloudrun
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cloudrun
  name: deployer-sample
spec:
  # TODO(user): Add fields here
