apiVersion: cloudapi.scs.buaa.edu.cn/v1alpha1
kind: Workflow
metadata:
  labels:
    app.kubernetes.io/name: workflow
    app.kubernetes.io/instance: workflow-sample
    app.kubernetes.io/part-of: cloudrun
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cloudrun
  name: workflow-sample
spec:
  round: 1
  builderList:
    - name: builder-sample
      namespace: default
  deployerList:
    - name: deployer-sample
      namespace: default
