apiVersion: cloudapi.scs.buaa.edu.cn/v1alpha1
kind: Builder
metadata:
  labels:
    app.kubernetes.io/name: builder
    app.kubernetes.io/instance: builder-sample
    app.kubernetes.io/part-of: cloudrun
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cloudrun
  name: builder-sample
  namespace: default
spec:
  context:
   raw: |
    FROM alpine:3.12
    CMD ["echo", "hello world"]
  dockerfilePath: Dockerfile
  destination: "docker.io/loheagn/cloudrun-test-image-builder:raw-8"
  pushSecretName: push-secret

