apiVersion: cloudapi.scs.buaa.edu.cn/v1alpha1
kind: Builder
metadata:
  labels:
    app.kubernetes.io/name: builder
    app.kubernetes.io/instance: builder-sample
    app.kubernetes.io/part-of: cloudrun
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cloudrun
  name: builder-sample
spec:
  # TODO(user): Add fields here
