apiVersion: cloudapi.scs.buaa.edu.cn/v1alpha1
kind: Deployer
metadata:
  labels:
    app.kubernetes.io/name: deployer
    app.kubernetes.io/instance: deployer-sample
    app.kubernetes.io/part-of: cloudrun
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cloudrun
  name: deployer-sample
spec:
  round: 4
  type: service
  resourcePool: resourcepool-sample
  containers:
    - image: nginx:1.20
      initial: false
      name: container-1
      ports:
        - port: 80
          protocol: tcp
          export: true
        - port: 8080
          protocol: tcp
          export: true
      env:
        somekey: somevalue
      resource:
        cpu: 200
        memory: 1000
